channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.16.0
  - attrs==23.2.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.1
  - scipy==1.14.0
  - tensorflow==2.16.2
name: mlflow-env
